### ISSUE TITLE
[Operation Crimson Heist] Flores

### ISSUE THREAD

**Issue by marcopixel** [marcopixel/r6operators#16]
## Flores

- **Role:** Attacker
- **Unit:** ?
- **Real name:** Santiago Lucero
- **Speed:** 2
- **Armor:** 2
> New infomation will be added to this issue as soon as it's available.

**Comment by danielwerg** [comment]
Unit: UNAFFILIATED
Real name: Santiago Miguel Lucero
![flores](https://user-images.githubusercontent.com/35052399/108916791-aab8ba80-7626-11eb-934d-e5b9a6bf35f5.png)

**Comment by marcopixel** [comment]
Sorry for the slow progress, i'll be hopefully able to add this icon on the weekend! If you want to get notified, please subscribe to this issue.

**Comment by Bl0n** [comment]
Here's the fankit with the high-res icon if you hadn't found that yet: https://ubi.li/crimsonheist_fankit

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/r6operators/commit/f9fce337d1a16229f72300d3813b99e85af1a29b, sorry for the delay.
