### ISSUE TITLE
Rework operator icons into the new style (translucent border)

### ISSUE THREAD

**Issue by SwiftCODA** [marcopixel/r6operators#22]
Hey. Just wondering if you can add the new-style icon for all the operators soon. If not, or if it will take a while, can you point me in the right direction to find the SVGs from Ubisoft natively?

Thanks.

**Comment by marcopixel** [comment]
Hello,

i've recently started working on the icons, so it will probably take a while for me to finish them since i'm also working on a rewrite of the library code itself and some other stuff too.

I cannot give a timeframe on when it will be finished, but i'll keep you guys updated on this issue.

I also cannot point you to some SVGs of the icons, since Ubisoft itself does not publish them as vector graphics. They only publish them as PNGs in their asset packs and only the newly released operators.

**Comment by joeyfoo** [comment]
I'll love to help out when I have free time - is there an update workflow or template or is it business as usual?

**Comment by marcopixel** [comment]
Sorry for the late response, i was on a vacation this weekend and haven't checked into Github until today.

There is a new template which you should use which contains the boundaries for the black and color border: https://drive.google.com/file/d/1yJEJGaczKpUidtpavt1MorFwdzMtfmv0/view

The black transparent part of the icon is `#000000` with a 25% opacity and should be exactly 260pt big.
Not sure if the guides show up on Inkscape, but if they don't the outer box is 260pt and the inner box (color background) is 200pt centered on 0,0.

**Comment by marcopixel** [comment]
@SwiftCODA Here are the new icons as a high-resolution PNGs, i can't guarantee that they're 1:1 to the official ingame icons but they should be the same :)

[r6icons.zip](https://github.com/marcopixel/r6operators/files/7117910/r6icons.zip)

**Comment by SwiftCODA** [comment]
@marcopixel Okay thanks man. I'll try to play around with them when I get a chance.

**Comment by SwiftCODA** [comment]
@marcopixel. I played around with the Osa icon and I got something that will work for now. Take a look and let me know what you think. https://www.icloud.com/iclouddrive/0lf-iKns0olwZf9EzDCwNKWmg#Osa

**Comment by marcopixel** [comment]
@SwiftCODA Good job, the icon looks pretty good so far but you need to keep the proportions in mind and don't forget the smaller details too 😃

If you want i would recommend you to try an older operator first because the newer operators have more detailed icons and thus are more complicated.

**Comment by OpticSkies** [comment]
Do we have a corrected Osa icon? Seems the one @SwiftCODA made is off and also in the .ai file format.

**Comment by marcopixel** [comment]
@OpticSkies Nope, i'm still working on redoing all of the icons and i'm currently about 60-65% done with all icons but i'll hope i can finish it until the new season drops.

Also i'm aware about the Thunderbird icon, but this also will be fixed in the future since i've adjusted the icon sizing for the new icons.

**Comment by OpticSkies** [comment]
Ok, can't wait! Thanks for the continuous work you've put into this.

**Comment by SwiftCODA** [comment]
@marcopixel I would like to try helping again. I'm pretty familiar with Illustrator. I don't quite understand how you can tike such a low resolution PNG and turn it into a high quality SVG. Where are you sourcing your original images from? Only place I can find most of the new ones is on Ubisoft's R6 page.

**Comment by marcopixel** [comment]
@SwiftCODA If you want, you could try yourself on the new operator **Thorn** (see #25) as we have a quite high-resolution screenshot of the new icon and i'm nearly done with all other operators (only ~10 left 😅).

@OpticSkies Here's the Osa icon: [Download](https://drive.google.com/file/d/13k51cP0wVa-4fneBEarMubUDVCJN9G-e/view)

**Comment by OpticSkies** [comment]
Yeah that's a great improvement. Not sure how to make it transparent or how to change it from an SVG to a PNG even though I could probably figure it out, but it's not exactly that important since you're almost done with the newest icons anyways. Btw, quick question, do you find these icons through the code, by recreating them, or is it a mixture of both?

**Comment by marcopixel** [comment]
@OpticSkies I did recreate all of the icons in Illustrator from scratch and I'm using high-res raster versions as a template.

So for the status, i'm pretty much done with all icons except Recruit & Thorn - has someone a high-quality version of that? @danielwerg @joeyfoo

**Comment by SwiftCODA** [comment]
@OpticSkies @marcopixel I have a png 1500px of Thorn. I can't guarantee it's accuracy cause I just did it from Image Trace in Illustrator 🤣. Hopefully it's enough to work with.
https://www.icloud.com/iclouddrive/0KaQoGCABVRqMKEv9c26K-xvg#thorn-full

**Comment by joeyfoo** [comment]
Sorry, no updates on my end, haven't found the motivation to work on it.

**Comment by danielwerg** [comment]
> Sorry for the late response, i was on a vacation this weekend and haven't checked into Github until today.
> 
> There is a new template which you should use which contains the boundaries for the black and color border: https://drive.google.com/file/d/1yJEJGaczKpUidtpavt1MorFwdzMtfmv0/view
> 
> The black transparent part of the icon is `#000000` with a 25% opacity and should be exactly 260pt big. Not sure if the guides show up on Inkscape, but if they don't the outer box is 260pt and the inner box (color background) is 200pt centered on 0,0.

Was looking for template just now, could you put a link in `CONTRIBUTING.md`?

**Comment by danielwerg** [comment]
> Sorry for the late response, i was on a vacation this weekend and haven't checked into Github until today.
> 
> There is a new template which you should use which contains the boundaries for the black and color border: https://drive.google.com/file/d/1yJEJGaczKpUidtpavt1MorFwdzMtfmv0/view
> 
> The black transparent part of the icon is `#000000` with a 25% opacity and should be exactly 260pt big. Not sure if the guides show up on Inkscape, but if they don't the outer box is 260pt and the inner box (color background) is 200pt centered on 0,0.

@marcopixel Was looking for template just now, could you put a link in `CONTRIBUTING.md`?
