### ISSUE TITLE
[Operation Crystal Guard] Osa

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#23]
## Character

* Name: Osa
* Role: Attacker
* Unit: NIGHTHAVEN

## Ratings:

* Speed: 2
* Armor: 2
* Difficulty: 2

## Metadata:

* Sex: ?
* Country: hr
* Season: Y6S3
* Height: 1.80m
* Weight: 71kg

## Biography

* Real name: Anja Katarina Janković
* Birthplace: Split, Croatia

## Icon

<details>
<summary>Click here to show the icon</summary>

![R6_Live_Y6S3_IMG_Op_Icon](https://user-images.githubusercontent.com/35052399/129939208-ec3098b7-3af3-41c3-95ca-eef85897cd58.png)

</details>

## Reference

<details>
<summary>Health/Speed/Difficulty</summary>

![20210818194602_1](https://user-images.githubusercontent.com/35052399/129939441-6f7810f3-80c8-4641-a72d-b8031e8df1ca.jpg)

</details>

<details>
<summary>Bio</summary>

![20210818194003_1](https://user-images.githubusercontent.com/35052399/129939459-6bdfffce-cc5c-47b6-9ed9-518ed6a85d3a.jpg)

</details>

**Comment by marcopixel** [comment]
Sorry for the late response, thanks for collecting all the necessary data for me :)

I've already started with the icon and i'll hope i can finish it in the next few days 👍

**Comment by SwiftCODA** [comment]
@marcopixel Do you recreate each icon from scratch in Illustrator or what is your process? I'm curious how you fabricate an SVG of each icon. I would be interested in helping to migrate some of the old icons to the newer style if you showed me how.

**Comment by marcopixel** [comment]
@SwiftCODA Yes, i'm doing every icon from scratch in Illustrator. Essentially i'm adding the raster image as a layer to Illustrator and then slowly recreate each layer/element on the icon. Sadly i haven't found the time recently (only made a few icons and the new library code itself) so there is no big progress right now, so any help would be appreciated :)

**Comment by SwiftCODA** [comment]
@marcopixel Where is a good source for your base image to start from?

**Comment by marcopixel** [comment]
@SwiftCODA Probably screenshotting the icons directly from the operator bio screen or somehow extracting the icons from the game itself.

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/r6operators/commit/fb519ca0aa3c3d05c0416eaeeb43fc7c6a09d790, thanks again for your help and patience :)
