### ISSUE TITLE
[Operation High Calibre] Thorn

### ISSUE THREAD

**Issue by marcopixel** [marcopixel/r6operators#25]
## Character

* Name: Thorn
* Role: Defender
* Unit: Garda ERU

## Ratings:

* Speed: 2
* Armor: 2
* Difficulty: 1

## Metadata:

* Sex: f
* Country: ?
* Season: Y6S4
* Height: ?
* Weight: ?

## Biography

* Real name: Brianna Skehan
* Birthplace: Ireland

## Icon
![image](https://user-images.githubusercontent.com/3743025/140819552-b79e0be3-1eda-42f7-b338-678059cb1c55.png)

**Comment by danielwerg** [comment]
Defender
2 Speed, 2 Armor, 1 difficulty
Garda ERU

Brianna Skehan
Ireland

**Comment by marcopixel** [comment]
@danielwerg Thanks for collecting the data for me, appreciated as always 👍

**Comment by danielwerg** [comment]
![](https://i.imgur.com/VDHh5Qv.png)
