### ISSUE TITLE
Rename "armor" to "health"

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#26]
`armor` should be renamed to `health` in https://github.com/marcopixel/r6operators/blob/master/src/operators.json

Thorn example:
![armor-health](https://user-images.githubusercontent.com/35052399/143326483-9e8bcaa9-6e95-4e29-b2e8-034fb58e1075.png)

**Comment by marcopixel** [comment]
@danielwerg Thanks, didn't even notice they changed it to health! 😅 

This has been changed on `next` and will probably be merged as soon as i'm finished with #22 (which should be done in the next few days).
