### ISSUE TITLE
Add operator cost (unlock prices)

### ISSUE THREAD

**Issue by leochras** [marcopixel/r6operators#28]
I would like to use the operator cost for a project, but this isn't a property yet, would it be possible to integrate this? I would help with this of course..

**Comment by leochras** [comment]
![image](https://user-images.githubusercontent.com/16163571/153655788-0e7e2acc-31d5-431e-a5bc-5bec4c0f9e13.png)

**Comment by leochras** [comment]
Hope this is useful
#29

**Comment by leochras** [comment]
Another question is: Which value does a recruit get? 0? Nan?

**Comment by leochras** [comment]
Hope I got everything right..
#30

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/r6operators/commit/f2f5b62a1c29b2b023126d1a9af8bca8dce1936f on Release 2.1.0.

Thanks again for your help 👍
