### ISSUE TITLE
Icon colour consistency

### ISSUE THREAD

**Issue by joeyfoo** [marcopixel/r6operators#3]
I noticed that some of the icons colours are not particularly consistent. For example, the lighter black fill colour for Alibi, Blackbeard, and Finka, compared to the deep/pure blacks used for the other icons.

Ideally, I'd like to also do a pass to make sure that colours are consistent within each CTUs when viewed side-by-side. The colours could also be adjusted with reference to official assets (but the priority would be to make sure it's internally consistent). 

I'd love to take this on, just popping an issue here to make sure there are no issues\* before I start.

*(P.S. I was going to discuss this on the R6DB Discord, but I see it's gone now?)*

*\* Pun not intended*

**Comment by marcopixel** [comment]
I've also wanted to do this a while ago, but never got the time to do it properly. If you want, you could join the [r6stats discord ](https://discord.gg/pUdraS3) where we can move the conversation into **#development** or just DM me on Discord :)

**Comment by joeyfoo** [comment]
I'm already in the R6Stats Discord: I'll drop a message there and here once I start!

**Comment by Bl0n** [comment]
Subscribing to this!
Especially the much lighter blacks in Maestro and Maverick are quite noticeable even if the icon is scaled down to like 35px x 35px as it is in my app.

**Comment by joeyfoo** [comment]
Oh god I haven't done any work on this since May 2020. If this is something we want to fix I can re-add this to my to-do list

**Comment by Bl0n** [comment]
My bad, I was just looking at the Flores addition, and didn't notice how old this issue was.
It's super low prio, but was definitely something I noticed as well.
Sorry for resurrecting this. 😬

**Comment by marcopixel** [comment]
Sorry for having no progress on this issue, had a few busy months and couldnt bring up the motiviation to start on this problem.

So the current list of high-priority icons are:
```
alibi
blackbeard
finka
lion
maestro
maverick
valkyrie
```

Those icons have either the most glaring issues regarding color/contrast and need to be fixed first, but eventually we need to update all icons before **May 2020** to adhere to the new template file which uses a slightly adjusted size (not by much, many icons are just 1-3pt off).

If anyone wants to start with the icons, i'll recommend you to start with the ones above. I'm also trying to fix at least one icon per week as long as i find enough time/motivation to do it 😅

**Comment by joeyfoo** [comment]
I'll also suggest assembling some form of colour palette so the updated colours are internally consistent.

**Comment by Bl0n** [comment]
Here are the following Operator icons SVG with the inconsistent light-grey changed to the black that all the other operator icons have:

```
alibi
blackbeard
finka
lion
maestro
maverick
valkyrie
```

[inconsistent_to_black_colour.zip](https://github.com/marcopixel/r6operators/files/6420941/inconsistent_to_black_colour.zip)

**Comment by marcopixel** [comment]
Well, since it seems that Ubisoft changed the style of the icons, i'm probably waiting for the test server or the official website to update if they do it across all their channels or if it's just for the icons ingame.

If they do indeed change all icons, this will take quite a while to update all the icons but it might be useful to properly set color rules as we've discussed before.

**Comment by marcopixel** [comment]
Can be closed because of the rework of the operator icons (see #22).
