### ISSUE TITLE
[Operation Demon Veil] Azami

### ISSUE THREAD

**Issue by marcopixel** [marcopixel/r6operators#31]
## Character

* Name: Azami
* Role: Defender
* Unit: ?

## Ratings:

* Speed: 2
* Health: 2
* Difficulty: ?

## Metadata:

* Sex: f
* Country: jp
* Season: Y7S1
* Height: ?
* Weight: ?

## Biography

* Real name: ???
* Birthplace: ???

## Icon
<details>
<summary>Click to show icon</summary>

![image](https://user-images.githubusercontent.com/3743025/154811958-83156e5e-67b2-4279-85c5-9c6dbc4f1ac9.png)

</details>

## Media
https://www.reddit.com/r/Rainbow6/comments/sw2u9a/just_saw_this_after_finishing_a_ranked_game_not/

**Comment by danielwerg** [comment]
Speed: 2
Armor: 2
![meta](https://user-images.githubusercontent.com/35052399/154810566-bab77510-48d2-4943-aa60-eae6a07198bf.png)
![icon](https://user-images.githubusercontent.com/35052399/154810570-f8b69056-e346-4515-8809-cde49bfac43b.png)

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/r6operators/commit/55612961add5b512896f388e31af96bb8f07f49c on Release 2.1.0
