### ISSUE TITLE
ETA on Sens?

### ISSUE THREAD

**Issue by SwiftCODA** [marcopixel/r6operators#33]
Hey man, you know how long until you will have Sens done?

Also,
I'm interested in listing you as a credit in my app, if you want. If so, what name do you want to go by?

**Comment by marcopixel** [comment]
Sorry about that, had some busy weeks recently and kinda forgot that the new operators have already released 😓

I'll should be able to finish them on the weekend as i'm currently sick and not feeling that well 😣

**Comment by marcopixel** [comment]
Added with Release 2.2.0, thanks for your patience :)
