### ISSUE TITLE
[Operation Vector Glare] Sens

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#35]
## Character

* Name: Sens
* Role: Attacker
* Unit: SFG

## Ratings:

* Speed: 1
* Armor: 3
* Difficulty: 2

## Metadata:

* Sex: ???
* Country: be
* Season: Y7S2
* Height: 1.78m
* Weight: 73kg

## Biography

* Real name: Néon Ngoma Mutombo
* Birthplace: Brussels, Belgium

## Icon

<details>
<summary>Click here to show the icon</summary>

![R6_Live_Y7S2_IMG_Op_Icon](https://user-images.githubusercontent.com/35052399/174066211-17319efe-15cf-41a8-a91e-2bb7beef73eb.png)

</details>

## Reference

<details>
<summary>Health/Speed/Difficulty</summary>

![sens ratings](https://user-images.githubusercontent.com/35052399/173701359-46c75cc2-a913-463c-8fd0-25da77509dea.png)

</details>

<details>
<summary>Bio</summary>

![sens bio](https://user-images.githubusercontent.com/35052399/173701386-43411f04-b8d6-4322-be8f-22bc680b44a2.png)

</details>

**Comment by danielwerg** [comment]
related: #33

**Comment by marcopixel** [comment]
Added with Release 2.2.0, thanks for your patience :)
