### ISSUE TITLE
[Operation Brutal Swarm] Grim

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#37]
## Character

* Name: Grim
* Role: Attacker
* Unit: NIGHTHAVEN

## Ratings:

* Speed: 3
* Health: 1
* Difficulty: 1

## Metadata:

* Sex: ???
* Country: sg
* Season: Y7S3
* Height: 1.79m
* Weight: 89.8kg

## Biography

* Real name: Charlie Tho Keng Boon
* Birthplace: Jurong, Singapore

## Icon

<details>
<summary>Click here to show the icon</summary>

![grim icon screenshot](https://user-images.githubusercontent.com/35052399/187552603-638fc143-7549-482c-b243-4c22074900d1.png)

![grim icon article](https://staticctf.akamaized.net/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/5VoAYPvRZXIwjcwTD3PWaZ/2530ce0b2d431f755265ac7d5804239d/r6s-operators-badge-grim.png)

</details>

## Reference

https://www.ubisoft.com/en-gb/game/rainbow-six/siege/game-info/seasons/brutalswarm

<details>
<summary>Health/Speed/Difficulty</summary>

![grim ratings](https://user-images.githubusercontent.com/35052399/186689053-58f8649c-84f2-4cec-aa6b-c6eac7f5292c.png)

</details>

<details>
<summary>Bio</summary>

![grim bio](https://user-images.githubusercontent.com/35052399/186689079-c9ed8b35-bd86-45f9-b000-c89a03d2cecf.png)

</details>

**Comment by SwiftCODA** [comment]
@marcopixel ETA on Grim icon?

**Comment by marcopixel** [comment]
Hello, sorry for the late response - i wasn't home this weekend so i could work on it yet but it's pretty easy so i should be done in the next few days 😄

**Comment by danielwerg** [comment]
New season about to drop so I tried creating grim icon myself, here is my first attempt using https://yqnn.github.io/svg-path-editor/ and https://aydos.com/svgedit/
```svg
<!-- Created By Daniel Werg (https://github.com/danielwerg) -->
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 350 350"
>
  <path style="opacity: 0.4;" d="M45 45h260v260H45z" />
  <path d="m171 142c30 0 30 48 0 50z" />
  <path style="fill: #d9c724;" d="M175 29 188 73 201 73 219 61 214 73H252L277 98V252L252 276 209 276 208 281 203 276 188 276 175 316M175 29 162 73 149 73 131 61 136 73H98L73 98V252L98 276 141 276 142 281 147 276 162 276 175 316" />
  <path d="M175 42 181 78Q181 80 183 82L193 86Q195 86 196 85L210 70 202 88Q200 91 202 93L208 99Q210 101 208 102L200 107Q198 110 201 112L265 135 322 204Q327 217 326 230L259 230 212 192Q213 179 209 176L191 159Q181 147 175 130M175 42 169 78Q169 80 167 82L157 86Q155 86 154 85L140 70 148 88Q150 91 148 93L142 99Q140 101 142 102L150 107Q152 110 149 112L85 135 28 204Q23 217 24 230L91 230 138 192Q137 179 141 176L159 159Q169 147 175 130" />
  <path style="fill: #ffffff;" d="M208 122 260 141 311 202Q316 207 316 212L317 224 307 224Q306 215 302 209L269 167 237 159Z" />
  <path style="fill: #ffffff;" d="M141 122 90 142 41 202Q36 207 36 212L35 224 51 224Q52 213 55 206L86 170 107 166Z" />
  <path style="fill: #ffffff;" d="M200 130 225 162 265 172 295 211Q297 217 297 223L284 223Q280 218 278 211L253 179 248 179 273 211Q276 216 276 223L264 223Q261 222 259 220L221 188 217 167Q216 164 213 160L193 135C189 128 195 124 200 130Z" />
  <path style="fill: #ffffff;" d="M150 130 118 169 91 176 68 203Q65 209 64 220L64 223 83 223C84 206 90 200 102 190L106 191C99 201 86 210 90 221L129 188 133 167Q134 164 137 160L157 135C161 128 155 124 150 130Z" />
  <path d="M175 142C181 159 179 163 197 176L205 200 226 222Q228 226 226 231L211 217Q208 216 208 220L208 248 198 260 204 273 196 264Q194 262 191 264L181 272 175 303M175 142C169 159 171 163 153 176L145 200 124 222Q122 226 124 231L139 217Q142 216 142 220L142 248 152 260 146 273 154 264Q156 262 159 264L169 272 175 303" />
  <path style="fill: #d9c724;" d="M175 163Q182 170 190 177L195 191 175 174M175 163Q168 170 160 177L155 191 175 174" />
  <path style="fill: #d9c724;" d="M175 186 204 213 204 227 175 200M175 186 146 213 146 227 175 200" />
  <path style="fill: #d9c724;" d="M175 219 203 244 196 252 175 233M175 219 147 244 154 252 175 233" />
  <path style="fill: #d9c724;" d="M175 249 186 257 175 265M175 249 164 257 175 265" />
</svg>
```

**Comment by marcopixel** [comment]
@danielwerg Thanks for your work, but i've already finished it before i saw your post here on Github 😅 Hope you're not mad for me using my icon now, since i've already commited everything and published it to NPM.

If you're quick next season with the icon i would probably use yours since i'm quite busy with live n' stuff right now 😅

**Comment by danielwerg** [comment]
Grim icon from fan kit:
![R6S_Y7S3_IMG_Operator_Icon](https://user-images.githubusercontent.com/35052399/190233409-822fa26a-90a1-43c0-9cdb-72ae6744002b.png)
