### ISSUE TITLE
[Operation Commanding Force] Brava

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#43]
## Character

- Name: Brava
- Role: Attacker
- ORG: COT
- SQUAD: Viperstrike

## Ratings:

- Speed: 3
- Health: 1
- Difficulty: 3

## Metadata:

- Sex: f
- Country: br
- Season: Y8S1
- Height: 1.70m
- Weight: 71kg

## Biography

- Real name: Nayara Cardoso
- Birthplace: Curitiba, Brazil

## Icon

<details>
<summary>Click here to show the icon</summary>

![2023-02-18_21-22-44 brava low res](https://user-images.githubusercontent.com/35052399/219900891-e3c9e95c-1e91-47e9-b3a4-25e867f3bf21.png)

![r6s-operators-badge-brava](https://user-images.githubusercontent.com/35052399/220218732-fcc2cb03-375c-43bd-8a18-c6e26fb63470.png)

![Brava_icon](https://user-images.githubusercontent.com/35052399/220219115-5906d5f2-fe2e-48f5-a007-9bbbe28de70c.png)

![brava operator selection](https://user-images.githubusercontent.com/35052399/220509871-0c7573ad-069d-4902-a884-d070828e8099.jpg)

![brava operator video](https://user-images.githubusercontent.com/35052399/220508252-bb30edbd-68dd-45d4-a745-68c2a6016144.jpg)

![R6S_Live_Y8S1_IMG_Brava_Badge_Icon](https://user-images.githubusercontent.com/35052399/224225591-0831f935-5c9a-4b98-9721-851a2e749f82.png)

</details>

## Reference

<details>
<summary>Health/Speed/Difficulty</summary>

![2023-02-18_21-23-03 brava ratings](https://user-images.githubusercontent.com/35052399/219900934-717c3602-46df-4fa0-b236-6b20b3a81db8.png)

</details>

<details>
<summary>Bio</summary>

![2023-02-18_21-44-05 brava bio](https://user-images.githubusercontent.com/35052399/219900912-b3fb6c6e-a6fb-43ce-b3e4-cb55fb011950.png)

</details>

**Comment by danielwerg** [comment]
<details><summary>Brava svg</summary>

```xml
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="350"
  height="350"
  viewBox="0 0 350 350"
>
  <path opacity="0.4" d="M45 45h260v260H45z"  />
  <path fill="#4eb3f8" d="M73 73h204v204H73z"  />
  <path fill-rule="evenodd" d="M112 25 205 92 214 90 222 67 252 146 261 133 320 109 254 202Q250 208 257 211L284 220 208 250 235 318 140 251Q133 245 131 254L124 284 93 205 24 237 92 141Q96 133 84 130L62 124 138 95ZM167 137l43 30-30 43-43-30Z" />
  <g fill="#ffffff">
    <path d="M125 43 203 99 217 95 223 81 249 150 232 174 207 109 202 126 141 84Z" />
    <path d="M210 167 227 180 216 195 218 199 236 205 196 220 212 260 150 214 143 219 140 236 111 167 82 206 41 222 97 144Q105 130 80 122L139 99 145 114C149 126 119 136 112 135L111 141 126 143 113 161 180 210Z" />
  </g>
</svg>
```

</details>

**Comment by Bl0n** [comment]
The actual operator icon colour as per Ubisoft sources is `#45abf3`, not the `#4eb3f8` you filled in with.
It's a subtle but definitely noticeable difference.

Having said that, amazing work on the .SVG! ❤

**Comment by danielwerg** [comment]
@Bl0n Thanks, updated it.

**Comment by SwiftCODA** [comment]
@marcopixel Can you update the repo with this?

**Comment by danielwerg** [comment]
Solved in https://github.com/marcopixel/r6operators/commit/afc28fa35fbb157e7e0d1d2ff1e04778dc45180f!
