### ISSUE TITLE
[Operation Dread Factor] Fenrir

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#45]
## Character

- Name: Fenrir
- Role: Defender
- ORG: Unaffiliated
- SQUAD: Redhammer

## Ratings:

- Speed: 2
- Health: 2
- Difficulty: 3

## Metadata:

- Sex: m
- Country: se
- Season: Y8S2
- Height: 1.76m
- Weight: 74kg

## Biography

- Real name: Emil Svensson
- Birthplace: Uppsala, Sweden

## Icon

<details>
<summary>Click here to show the icon</summary>

![623990_20230517075453_1_proc](https://github.com/marcopixel/r6operators/assets/35052399/15d4dac7-8f93-4889-bf3b-ff6d2ad2cd91)

</details>

## Reference

<details>
<summary>Health/Speed/Difficulty</summary>

![1](https://github.com/marcopixel/r6operators/assets/35052399/5d2fd89d-8410-4143-8333-0146e3dc76f8)

</details>

<details>
<summary>Bio</summary>

![2](https://github.com/marcopixel/r6operators/assets/35052399/aa4c57f8-b133-46cd-954a-4d131a33e519)

</details>

**Comment by danielwerg** [comment]
###### working on the icon...

**Comment by Bl0n** [comment]
Accurate color (Ubisoft source) #6432ef

**Comment by danielwerg** [comment]
> Accurate color (Ubisoft source) #6432ef

Hmmm, how come I get `#5f51bf` when taking lossless screenshot in-game?

**Comment by danielwerg** [comment]
@Bl0n updated my first comment.

**Comment by danielwerg** [comment]
Solved in https://github.com/marcopixel/r6operators/commit/557b359e7af2e9d761a67a58739e19c4ba6e41e2!
