### ISSUE TITLE
Feedback for Ram icon

### ISSUE THREAD

**Issue by danielwerg** [marcopixel/r6operators#47]
## svg file is over 4k lines because `image` element was left

![2023-09-04_23-17-19](https://github.com/marcopixel/r6operators/assets/35052399/7728d184-7829-446b-8f42-e17695158062)

## Little triangle on picture below should *probably* be same black color instead of transparent

![2023-09-04_23-16-24](https://github.com/marcopixel/r6operators/assets/35052399/30b500c0-cb3a-4113-bf7a-d23e99692e8c)

Not sure which exact color should be used for black, `#000000` is fine I guess but in-game it's `#121616` and in assets packs it's `#040707`

## I'm getting nitpicky...There should be straight lines instead of curves in place of red line, blue lines represent where V thingy should *roughly* be cut (it's uneven)

![2023-09-04_23-39-34](https://github.com/marcopixel/r6operators/assets/35052399/60b01a2c-44ba-4ecf-b6d4-a808c8acf335)

###### Compared to `Y8S3_BADGE_Ram_L`

---

<details>
<summary>refs</summary>

### Y8S3_BADGE_Ram_L

![Y8S3_BADGE_Ram_L](https://github.com/marcopixel/r6operators/assets/35052399/6c5d2186-ec57-4a9d-b827-e4de724f0574)

### Y8S3_BADGE_Ram_M

![Y8S3_BADGE_Ram_M](https://github.com/marcopixel/r6operators/assets/35052399/b59e8e8f-7408-41f2-bbe0-48160cbc36cb)

### Ram icon in-game

![ram icon in-game](https://github.com/marcopixel/r6operators/assets/35052399/6dbc3942-e229-4edf-b8ae-fc48c07953b3)

</details>

**Comment by marcopixel** [comment]
Should be fixed now, thanks for your feedback 👍
