### ISSUE TITLE
Icon request: ranks

### ISSUE THREAD

**Issue by K0ney** [marcopixel/r6operators#5]
Would it be possible to include the ranks as well? The project is called r6operators, but it would be cool if you could include the ranks in the project.

**Comment by marcopixel** [comment]
Sadly this is out of the scope for this (for now, maybe i'll do a r6ranks project), but you can get the official SVG icons from Ubisoft here: https://game-rainbow6.ubi.com/assets/data/ranks.31c8c84c.json
